-- Create the "projects" table
CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    title TEXT NOT NULL,
    client TEXT,
    category TEXT,
    cover_image TEXT,
    gallery_images JSONB DEFAULT '[]'::jsonb,
    description TEXT,
    content TEXT,
    is_featured BOOLEAN DEFAULT FALSE NOT NULL,
    project_link TEXT
);

-- Optional but recommended: Add comments to your columns for clarity
COMMENT ON COLUMN projects.title IS 'The name of the design project';
COMMENT ON COLUMN projects.client IS 'The client''s name or "Personal Project"';
COMMENT ON COLUMN projects.category IS 'The type of design (e.g., "UI/UX", "Branding")';
COMMENT ON COLUMN projects.cover_image IS 'The primary thumbnail image for the grid';
COMMENT ON COLUMN projects.gallery_images IS 'An array of all project image URLs';
COMMENT ON COLUMN projects.description IS 'Short summary for the project card';
COMMENT ON COLUMN projects.content IS 'Full case study content (can support Markdown)';
COMMENT ON COLUMN projects.is_featured IS 'True to pin or feature a project on the homepage';
COMMENT ON COLUMN projects.project_link IS 'Optional link to the live project or Behance/Dribbble page';

-- Enable Row Level Security (RLS) on the table.
-- While we disable it for the tutorial, it's good practice to enable it.
-- Our service_role key will bypass this, but it adds a layer of security.
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow public read access to all projects.
-- This means anyone can view the projects, which is what we want for a portfolio.
CREATE POLICY "Allow public read access" ON projects
FOR SELECT USING (true);